name: nest-starter-prod
services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
      # - ./:/usr/src/app # Mount the local `src` folder to `/usr/src/app` in the container
    environment:
      - DATABASE_URL=postgresql://nodeProdUser:postgresPasswword@nest-starter-postgres:5432/nest_starter
      - SMTP_HOST=mailhog


  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8026:8025

  postgres:
      container_name: nest-starter-postgres
      image: postgres:15.4
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=nest_starter

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80" # Expose port 8080 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom Nginx config
      - ./html:/usr/share/nginx/html:ro # Serve static files

    depends_on:
      - app
      
