name: nest-starter
version: '3.7'
services:
  postgres:
      image: postgres:15.4
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=node_pretaa_testing
      ports:
        - '5433:5432'

      # postgresql://nodeProdUser:postgresPasswword@localhost:5433/node_pretaa_testing
