name: nest-starter
version: '3.7'
services:

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  postgres:
      container_name: postgres
      image: postgres:15.4
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=nest_starter
      ports:
        - '5433:5432'
      # postgresql://nodeProdUser:postgresPasswword@localhost:5433/nest_starter

      
