name: nest-starter
version: '3.7'
services:

  # app:
  #   container_name: app
  #   build:
  #     context: .
  #   volumes:
  #     - ./:/usr/src/app # Mount the local `src` folder to `/usr/src/app` in the container
  #   ports:
  #     - "4000:4000"

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  postgres:
      container_name: postgres
      image: postgres:15.4
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=nest_starter
      ports:
        - '5433:5432'
      # postgresql://nodeProdUser:postgresPasswword@localhost:5433/nest_starter

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8080:80" # Expose port 8080 on the host to port 80 in the container
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom Nginx config
  #     - ./html:/usr/share/nginx/html:ro # Serve static files

  #   depends_on:
  #     - app
      
