name: nest_starter_prod
services:
  mailhog:
    container_name: nest_starter_prod_mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8026:8025

  postgres:
      container_name: nest_starter_prod_postgres
      image: postgres
      environment:
        - POSTGRES_PASSWORD=postgresPasswword
        - POSTGRES_USER=nodeProdUser
        - POSTGRES_DB=nest_starter
      ports:
        - '5434:5432'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80" # Expose port 8080 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom Nginx config

    depends_on:
      -  app
      
  app:
    container_name: nest_starter_prod_app
    image: itobuz/nest-starter-backend-arm
    env_file: 
      - .env.production
