name: nest_starter_prod
services:
  mailhog:
    container_name: nest_starter_prod_mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8036:8025

  postgres:
      container_name: nest_starter_prod_postgres
      image: postgres:latest
      ports:
        - '8040:5432'
      volumes:
        - ./tmp/db/postgresql:/var/lib/postgresql/data
      env_file: 
      - .env.production
  
      
  backend:
    container_name: nest_starter_prod_backend
    image: itobuz/nest-starter-backend-arm
    env_file: 
      - ../.env.production
    ports:
      - "8037:4000" # Expose port 8080 on the host to port 80 in the container


  frontend:
    container_name: nest_starter_prod_webapp
    image: itobuz/nest-starter-webapp
    env_file: 
      - .env.production
    ports:
      - "8038:80"

  nginx:
      image: nginx:latest
      container_name: nest_starter_prod_webapp_api_gateway
      ports:
        - "8039:80" # Expose port 8080 on the host to port 80 in the container
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom Nginx config

      depends_on:
        -  backend